//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam1_7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineExamEntities : DbContext
    {
        public OnlineExamEntities()
            : base("name=OnlineExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<FillBlankProblem> FillBlankProblems { get; set; }
        public virtual DbSet<JudgeProblem> JudgeProblems { get; set; }
        public virtual DbSet<MultiProblem> MultiProblems { get; set; }
        public virtual DbSet<Paper> Papers { get; set; }
        public virtual DbSet<PaperDetail> PaperDetails { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<SingleProblem> SingleProblems { get; set; }
        public virtual DbSet<StudentExam> StudentExams { get; set; }
        public virtual DbSet<StudentFillBlankProblem> StudentFillBlankProblems { get; set; }
        public virtual DbSet<StudentJudgeProblem> StudentJudgeProblems { get; set; }
        public virtual DbSet<StudentMultiProblem> StudentMultiProblems { get; set; }
        public virtual DbSet<StudentSingle> StudentSingles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
